# Site settings
title: Jordan Réjaud
email: jrejaud@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Random thoughts about programming, math, and sometimes philosophy
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.jordanrejaud.com" # the base hostname & protocol for your site
twitter_username: jordanrejaud
github_username:  jrejaud

# Build settings
markdown: kramdown
