# Site settings
title: Jordan Réjaud
email: jrejaud@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Random thoughts about programming, math, and sometimes philosophy
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jordanrejaud.com" # the base hostname & protocol for your site
twitter_username: jordanrejaud
github_username:  jrejaud

# Build settings
markdown: redcarpet
#used to be kramdown
redcarpet:
 # Copied from http://stackoverflow.com/questions/16099153/table-not-render-when-use-redcarpet-in-jekyll-github-pages
 extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "strikethrough", "superscript", "with_toc_data"]
